Support for Alfa bank
gerasiov/ofxstatement-russian pull request #5
Opened 2017-06-24 13:15 UTC by zeldigas

Hi I added support for AlfaBank csv format. Tests are included.

2017-07-11 19:58 UTC, gerasiov requested changes
Please fix thees minor issues.

2017-07-11 19:58 UTC, gerasiov commented on README.rst
> +        (default is 'SberBank')
AlfaBank

2017-07-11 19:58 UTC, gerasiov commented on setup.py
> +      keywords=["ofxstatement", "russian", "avangard", "tinkoff", "sberbank", 'alfabank'],
Please follow coding style. Do not mix different type of quote-sign.

2017-07-11 19:58 UTC, gerasiov commented on src/ofxstatement/plugins/alfabank.py
> +#
Didn't you forget to mention me in this copyright note? =)

2017-07-13 19:13 UTC, zeldigas commented on setup.py
> +      keywords=["ofxstatement", "russian", "avangard", "tinkoff", "sberbank", 'alfabank'],
OK, will fix

2017-07-13 19:15 UTC, zeldigas commented on src/ofxstatement/plugins/alfabank.py
> +#
I thought that only author is listed and I don't see contributions  ;).  if you think that plugin structure is a good reason to add you here (of course I took it from tinkoff one to follow single coding style) I'm fine to add you

2017-07-14 16:50 UTC, gerasiov commented on src/ofxstatement/plugins/alfabank.py
> +#
I just see, that this code is based on one I wrote. =) Technically this is derived work and you should mention original author. (Not critical for me, but I believe there is some kind of good behavior pattern open source developer should follow.)

2017-07-15 08:04 UTC, zeldigas commented
CR fixes pushed

2017-07-17 16:55 UTC, gerasiov approved these changes

2017-07-17 17:04 UTC, merged